### ISSUE TITLE
Идеи для ачивок

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#1]

**Comment by qelphybox** [comment]
Безработный - больше всего сообщений, за последние 5 рабочих дней с 10:00 до 18:00

**Comment by finzr** [comment]
Работяга - меньше всего сообщений, за последние 5 рабочих дней с 10:00 до 18:00

**Comment by finzr** [comment]
Поставщик контента - человек, который за последние 5 рабочих дней с 10:00 до 18:00 скинул больше всего файлов.
можно разветвить на N ачивок (Поставщик пикч, поставщик видосов, поставщик новостей).

**Comment by finzr** [comment]
Человек-стикер  - человек, который за последние 5 рабочих дней с 10:00 до 18:00 скинул больше всего стикеров.

**Comment by AlexanderMalikh** [comment]
Очень плохой человек - скинул больше всех голосовух за последние 5 рабочих дней с 10:00 до 18:00.
Дневальный - больше всего первых постов после 6 утра, за последние 5 рабочих дней с 06:00 до 18:00.

**Comment by finzr** [comment]
Доёбщик - человек, который за последние 5 рабочих дней с 10:00 до 18:00 больше всего задавал вопросов.

**Comment by stansaal** [comment]
Диск-жокей - человек, который за последнюю неделю пересылал больше всех сообщений от vk music bot (нужно предусмотреть список популярных ботов с музыкой вк)

**Comment by appdrop** [comment]
Настоящий друг — чаще всех отвечает на сообщения других

**Comment by appdrop** [comment]
Философ — самое большое количество символов на сообщение

**Comment by appdrop** [comment]
Строгий — чаще других ставит точки в конце сообщений

Веселый — большее количество эмоджи

Миллениал — много несловарных слов в сообщениях

Дудь — чаще всех задаёт вопросы

Забытый — кто долго уже не пишет сообщения

**Comment by stansaal** [comment]
Нетворкер - чаще всех приглашает людей в чат

**Comment by marselmustafin** [comment]
Юморист - челвек с больше количеством реплаев вида "ахахаххахахах"

**Comment by qelphybox** [comment]
@marselmustafin Классная ачивка, спасибо!
