### ISSUE TITLE
Добавить ачивку "Философ чата"

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#11]
Философ чата (chatPhilosopher) — имеет самую большую медиану длины сообщения в чате. То есть считаем каждодому юзеру чата медиану, то у кого это самое большое число - философ.
Пример алгоритма медианы: https://repl.it/@qelphybox/jsmedianexample
Круто будет сделать одним агрегационным запросом в бд.

Алгоритм:
Каждому юзеру считаем длину каждого его сообщения от начала времен (значит нижняя граница не нужна, считаем по всем сообщениям). Для каждого юзера будет как бы массив длин сообщений `{ user1: [5,6,7,8,9, ...], ...}` 
Затем каждому юзеру находим медиану этого массива: получится  например `{ user1: 9, ... }`
Находим юзера с самым большим числом. Если их несколько, выводим всех.

вывод:
```
**username** - философ чата (345 сообщений по медиане)
// если несколько
**username1**, **username2** - философы чата (345 сообщений по медиане)
```

**Comment by DmitryBara** [comment]
Сделаю!

**Comment by qelphybox** [comment]
> Сделаю!

@DmitryBara Спасибо :+1:  Буду ждать пул реквеста!

**Comment by Johnny32id** [comment]
Беру.

**Comment by qelphybox** [comment]
@Johnny32id спасибо :+1: Ждем пулреквеста
