### ISSUE TITLE
Уборка тестов

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#132]
- [ ] Оставьте только actions тесты, тесты отдельных статистик не нужны, удалите их и все что с ними связано.
- [ ] actions тесты нужно раскидать по файлам, в зависимости от тестируемого функционала. Например, файл с тестированием статистики безработного, файл с тестированием статистики стикерпакера и тд.

**Comment by Johnny32id** [comment]
Беру.

**Comment by qelphybox** [comment]
@Johnny32id спасибо :ok_hand: , жду pr!
