### ISSUE TITLE
Ачивка "Юморист"

### ISSUE THREAD

**Issue by marselmustafin** [qelphybox/hakeshonassybot#138]
Идея ачивки - человек с наибольшим количеством реакций, обозначающих смех. В реакции могут входить:

1. Текст содержащий последовательности вида "ахахахах"
2. Эмодзи обозначающие смех
3. Аббревиатуры означающие смех - лол, кек

В пункте 1 следует учесть возможные опечатки, раскладку (f[f[f[f), регистр, производные формы (хех, хихи)

**Comment by qelphybox** [comment]
@marselmustafin Круто, спасибо! Я думаю стоит матчить просто наличие в тексте "ахах", "хаха", "хехе", "ехех" и тд. В общем два слога для матча достаточно, про раскладку круто подметил. Стикеры я тоже думаю стоит учитывать.

**Comment by qelphybox** [comment]
@marselmustafin Ещё предлагаю собирать стат по ачивке за последние 7 суток (7 * 24 часа), а то у нас есть проблема что ачивка не слезает с юзера.

**Comment by smthingwicked** [comment]
Беру
