### ISSUE TITLE
Доработать ачивку Философ чата

### ISSUE THREAD

**Issue by Johnny32id** [qelphybox/hakeshonassybot#140]
Ограничить выборку сообщений до месяца, но не так чтобы отсчёт был от текущей даты -30, а с первого дня каждого месяца. То есть сообщения написанные 30-31 числа прошлого месяца не учитывались.

**Comment by qelphybox** [comment]
@Johnny32id Предлагаю сделать "Философ недели" чтобы ачивки выглядели универсально

**Comment by Johnny32id** [comment]
Если больше предложений нет, то берусь переделать на Философа недели.
