### ISSUE TITLE
Сверстать страницы для вебморды

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#154]
Дизайн: https://www.figma.com/file/cJUtYaG9QxcVZB9fFntQtt/Hake-Shonassy?node-id=0%3A1

**Comment by Johnny32id** [comment]
Беру.

**Comment by qelphybox** [comment]
Разбил этот таск на https://github.com/qelphybox/hakeshonassybot/issues/180 и https://github.com/qelphybox/hakeshonassybot/issues/181. @Johnny32id возьми https://github.com/qelphybox/hakeshonassybot/issues/180 плз
