### ISSUE TITLE
Реализовать авторизацию на бэке

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#166]
Нужно написать авторизацию через телеграм, тут вся полезная инфа https://core.telegram.org/widgets/login

Авторизация через callback поэтому на бэке нужно реализовать пару методов:
1) `GET /auth/callback?id=asdf&first_name=asdf&last_name=asdf&username=asdf&photo_url=asdf&auth_date=asdfhash=asdf`
    1) Провалидировать запрос (https://core.telegram.org/widgets/login#checking-authorization)
    1) Если запрос валиден: Сохранить данные юзера в сессию (в куки) и редирект на Home page (304) `/?auth=success`
    1) Если запрос невалиден: Редирект на Home page (304) `/?auth=fail`
2) `GET /auth/logout`
    1) Удалить из сессии данные юзера
    1) Вернуть 200 `{ "message": "Bye!" }`

Можно сделать тестовые welcome page и home page чтобы можно было протыкать весь процесс.

**Comment by svyborov** [comment]
Беру.
