### ISSUE TITLE
Выделить слой actions

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#30]
У нас постоянно какие-то баги после выкатки, в итоге мы всегда выкатываемся в несколько раундов, чтобы это избежать нам нам нужно как можно более верхнеуровневое тестирование.
Приемлемый уровень, имхо, функции которыми мы реагируем на  события в телеграме, нужно выделить в модуль и плотно закрыть его тестами.

**Comment by svyborov** [comment]
Реализовать следующие тест кейсы:

Безработный
1. user1 пишет 2 сообщения в 11.00 МСК
2. user2 пишет 1 сообщение в 12.00 МСК
3. user3 пишет 3 сообщения в 19.00 МСК
4. user1 пишет /stats и получает что user1 - безработный (через includes)


Худщший юзер чата
1. user1 отправляет 1 головосое сообщение
2. user2 отправляет 2 голосовых сообщение
4. user1 пишет /stats и получает что user2 - худший бзер чата (через includes)

Поставщик контента
1. user1 отправляет картинку в чат
2. user2 отправляет картинку и видео
4. user1 пишет /stats и получает что user2 - Поставщик контента (через includes)

24 часа
1. user1 пишет 23 сообщения в чат через каждый час
2. user2 пишет каждый четный час
3. user3 пишет кратныый 3 час
4. user1 пишет /stats и получает что за 24 часа user1 - 23, user2 - 11, user3 - 7

За час // по той же схеме что и 24
1. user1 пишет каждую минуту сообщение
2. user2 пишет каждые 10 минут сообщение
3. user3 пишет каждые 20 минут сообщение
4. user1 пишет /stats и получает что за 24 часа user1 - 23, user2 - 11, user3 - 7
