### ISSUE TITLE
Обнулять счётчик ачивок

### ISSUE THREAD

**Issue by Spielmannmisha** [qelphybox/hakeshonassybot#42]
**Описание ошибки**
На данный момент часть ачивок редко активируются и при выводе /stats можно месяцами видеть одного  и того же человека под определённой ачивкой.

Предлагаю в вывод /stats показывать только те ачивки, которые активировались в промежутке последних 7 дней.

**Comment by qelphybox** [comment]
Спасибо за ишью!

Счетчик не так работает, тут скорее нужно по каждой ачивке в отдельности говорить. 
1) Худший юзер чата - тот кто скинул в чат больше всего голосовых сообщений за все время
2) Безработный - тот кто за последние 5 рабочих дней написал больше сообщений в рабочее время (с 10 до 18 мск).
3) Поставщик контента - тот кто больше всего фото и видео скинул за все время.

С какими ачивками именно проблема?

**Comment by qelphybox** [comment]
Пока информации не достаточно переоткроем если будут обновления
